def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
	agent any
	tools {
		jdk "OracleJDK8"
                maven "MAVEN3.9"
		}
	environment {
		cluster = "vproprod"
		service = "vproappprodsvc"
		}
	stages{
		stage('Deploy to ECS Production') {
			steps {
				withAWS(credentials: 'awscreds', region: 'ap-south-1') {
					sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
					}
				}
			}
		}
	post {
		always {
			echo 'Slack Notifications.'
			slackSend channel: '#jenkinscicdchannel',
				color: COLOR_MAP[currentBuild.currentResult],
				message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
			}
		}
	}
