def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
	agent any
	tools {
		jdk "OracleJDK11"
         	maven "MAVEN3.9"
		}
  environment {
		SNAP_REPO = 'devops-snapshots'
                NEXUS_USER = 'admin'
                NEXUS_PASS = 'ramya@WL123'
                RELEASE_REPO = 'devops-release'
                CENTRAL_REPO = 'devops-central'
                NEXUSIP = '18.222.73.250'
                NEXUSPORT = '8081'
                NEXUS_GRP_REPO = 'devops-group'
                NEXUS_LOGIN = 'nexuslogin'
	  	SONARSERVER = 'sonarserver'
        	SONARSCANNER = 'sonarscanner'
	  	registryCredential = 'ecr:us-east-2:awscreds'
                appRegistry = '590183829524.dkr.ecr.us-east-2.amazonaws.com/vprofileappimg'
                vprofileRegistry = "https://590183829524.dkr.ecr.us-east-2.amazonaws.com"
		}
  stages{
  		stage('BUILD'){
  			steps {
  				sh 'mvn -s settings.xml -DskipTests install'
  				}
			post {
				success {
					echo "Archiving"
					archiveArtifacts artifacts: '**/*.war'
						}
				}
  		}
	  	stage('Test') {
			steps {
				sh 'mvn -s settings.xml test'
			}
		}
	  	stage('Checkstyle Analysis') {
			steps {
				sh 'mvn -s settings.xml checkstyle:checkstyle'
			}
		}
	  	stage('Sonar Analysis') {
           		 environment {
                	scannerHome = tool "${SONARSCANNER}"
           	 		}
		            steps {
		               withSonarQubeEnv("${SONARSERVER}") {
		                   sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
		                   -Dsonar.projectName=vprofile \
		                   -Dsonar.projectVersion=1.0 \
		                   -Dsonar.sources=src/ \
		                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
		                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
		                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
		                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
		              	}
		            }
      		  }
	  	stage("Quality Gate") {
			steps {
				timeout(time: 1, unit: 'HOURS') {
                    // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
                    // true = set pipeline to UNSTABLE, false = don't
					waitForQualityGate abortPipeline: true
					}
				}
			}
	  stage("UploadArtifact"){
			steps{
				nexusArtifactUploader(
                                nexusVersion: 'nexus3',
                                protocol: 'http',
                                nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
                                groupId: 'QA',
                                version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                                repository: "${RELEASE_REPO}",
                                credentialsId: "${NEXUS_LOGIN}",
                                artifacts: [
					[artifactId: 'vproapp',
					 classifier: '',
					 file: 'target/vprofile-v2.war',
					 type: 'war']
					]
					)
			}
		}
	   stage('Build App Image') {
			 steps {
				 script {
					 dockerImage = docker.build( appRegistry + ":$BUILD_NUMBER", "./Docker-files/app/multistage/")
					 }
				 }
			 }
	 
	 
      }
	post {
		always {
			echo 'Slack Notifications.'
			slackSend channel: '#jenkinscicd',
				color: COLOR_MAP[currentBuild.currentResult],
				message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
			}
		}
}
